# Generated by Django 3.0.5 on 2020-04-23 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(default='000-00/20', help_text='Введи в фомате ннн-мм/гг', max_length=32, verbose_name='Номер отчета (договора)')),
                ('inspection_date', models.DateField(default=datetime.date.today, verbose_name='Дата осмотра (договора)')),
                ('calculation_date', models.DateField(default=datetime.date.today, verbose_name='Дата расчета')),
                ('client_name', models.CharField(default='Н/у', help_text='Введи Ф.И.О. полностью', max_length=128, verbose_name='Ф.И.О. заказчика')),
                ('ownership_identification', models.CharField(choices=[('1', 'Частная собственность'), ('2', 'Муниципальная собственность'), ('3', 'Государственная собственность'), ('4', 'Н/у')], default='1', max_length=128, verbose_name='Право собственности')),
                ('inspection_place', models.CharField(default='Н/у', help_text='Введи хотя бы населенный пункт', max_length=128, verbose_name='Место осмотра:')),
                ('evaluation_purpose', models.CharField(choices=[('1', 'Определение стоимости ущерба, причиненного вследствие дорожно-транспортного происшествия'), ('2', 'Определение стоимости ущерба, причиненного вследствие возгорания транспортного средства'), ('3', 'Определение стоимости причиненного ущерба')], default='1', max_length=128, verbose_name='Цель оценки')),
                ('results_purpose', models.CharField(choices=[('1', 'Для возмещения убытков (ст. 14 ГК КР)'), ('2', 'Для страховой выплаты'), ('3', 'Для принятия управленческих решений')], default='1', max_length=128, verbose_name='Назначение результатов оценки')),
                ('cost_type', models.CharField(choices=[('1', 'Рыночная стоимость восстановления транспортного средства'), ('2', 'Рыночная стоимость восстановления и утрата товарной стоимости транспортного средства')], default='1', max_length=128, verbose_name='Вид определяемой стоимости')),
                ('contract_price', models.IntegerField(default=0, verbose_name='Сумма оплаты (договора)')),
                ('vehicle_model', models.CharField(default='Н/у', max_length=128, verbose_name='Марка, модель ТС')),
                ('vehicle_year', models.CharField(default='Н/у', max_length=4, verbose_name='Год выпуска')),
                ('vehicle_regnum', models.CharField(default='Н/у', max_length=32, verbose_name='Гос. (рег.) номер ТС')),
                ('vehicle_vin', models.CharField(default='Н/у', max_length=32, verbose_name='Номер кузова (VIN)')),
                ('vehicle_frame', models.CharField(default='Н/у', max_length=32, verbose_name='Номер рамы (шасси)')),
                ('vehicle_passport', models.CharField(default='Н/у', max_length=32, verbose_name='Номер техпаспорта')),
                ('vehicle_volume', models.CharField(default='Н/у', max_length=16, verbose_name='Объем ДВС')),
                ('vehicle_mileage', models.CharField(default='Н/у', max_length=16, verbose_name='Пробег')),
                ('vehicle_color', models.CharField(default='Н/у', max_length=32, verbose_name='Цвет')),
                ('vehicle_type', models.CharField(default='Н/у', max_length=32, verbose_name='Тип ТС')),
                ('vehicle_body', models.CharField(default='Н/у', max_length=32, verbose_name='Тип кузова ТС')),
                ('vehicle_owner', models.CharField(default='Н/у', max_length=256, verbose_name='Владелец ТС')),
                ('vehicle_adress', models.CharField(default='Н/у', max_length=256, verbose_name='Адрес регистрации ТС')),
                ('hourcost', models.IntegerField(default=600, verbose_name='Стоимость нормо-часа')),
                ('disassembly_text', models.TextField(default='Н/у', verbose_name='Текст разборок')),
                ('repair_text', models.TextField(default='Н/у', verbose_name='Текст ремонтов')),
                ('painting_text', models.TextField(default='Н/у', verbose_name='Текст окраски')),
                ('additional_text', models.TextField(default='Н/у', verbose_name='Текст доп. работ')),
                ('hidden_text', models.TextField(default='Н/у', verbose_name='Текст скрытых повреждений')),
                ('parts_text', models.TextField(default='Н/у', verbose_name='Текст запчастей')),
                ('services_table', models.TextField(default='', verbose_name='Таблица услуг')),
                ('materials_table', models.TextField(default='', verbose_name='Таблица материалов')),
                ('parts_table', models.TextField(default='', verbose_name='Таблица запчастец')),
            ],
        ),
    ]
