# Generated by Django 3.0.5 on 2020-04-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='contract_price_in_words',
            field=models.CharField(default='Ноль', max_length=128, verbose_name='Сумма оплаты (прописью)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='materials_table',
            field=models.TextField(blank=True, default='', verbose_name='Таблица материалов'),
        ),
        migrations.AlterField(
            model_name='report',
            name='parts_table',
            field=models.TextField(blank=True, default='', verbose_name='Таблица запчастец'),
        ),
        migrations.AlterField(
            model_name='report',
            name='services_table',
            field=models.TextField(blank=True, default='', verbose_name='Таблица услуг'),
        ),
    ]
