# Generated by Django 3.0.5 on 2020-04-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200425_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='additional_text',
            field=models.TextField(default='', verbose_name='Текст доп. работ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cost_type',
            field=models.CharField(choices=[('Рыночная стоимость восстановления транспортного средства', 'Рыночная стоимость восстановления'), ('Рыночная стоимость восстановления и утрата товарной стоимости транспортного средства', 'Рыночная стоимость восстановления и ТС')], default='Рыночная стоимость восстановления транспортного средства', max_length=128, verbose_name='Вид определяемой стоимости'),
        ),
        migrations.AlterField(
            model_name='report',
            name='disassembly_text',
            field=models.TextField(default='', verbose_name='Текст разборок'),
        ),
        migrations.AlterField(
            model_name='report',
            name='evaluation_purpose',
            field=models.CharField(choices=[('Определение стоимости ущерба, причиненного вследствие дорожно-транспортного происшествия', 'ДТП'), ('Определение стоимости ущерба, причиненного вследствие возгорания транспортного средства', 'Возгорание'), ('Определение стоимости причиненного ущерба', 'Прочий ущерб')], default='Определение стоимости ущерба, причиненного вследствие дорожно-транспортного происшествия', max_length=128, verbose_name='Цель оценки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hidden_text',
            field=models.TextField(default='', verbose_name='Текст скрытых повреждений'),
        ),
        migrations.AlterField(
            model_name='report',
            name='materials_table',
            field=models.TextField(blank=True, default='', verbose_name='Таблица материалов (JSON)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ownership_identification',
            field=models.CharField(choices=[('Частная собственность', 'Частная'), ('Муниципальная собственность', 'Муниципальная'), ('Государственная собственность', 'Государственная'), ('Н/у', 'Н/у')], default='Частная собственность', max_length=128, verbose_name='Право собственности'),
        ),
        migrations.AlterField(
            model_name='report',
            name='painting_text',
            field=models.TextField(default='', verbose_name='Текст окраски'),
        ),
        migrations.AlterField(
            model_name='report',
            name='parts_table',
            field=models.TextField(blank=True, default='', verbose_name='Таблица запчастец (JSON)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='parts_text',
            field=models.TextField(default='', verbose_name='Текст запчастей'),
        ),
        migrations.AlterField(
            model_name='report',
            name='repair_text',
            field=models.TextField(default='', verbose_name='Текст ремонтов'),
        ),
        migrations.AlterField(
            model_name='report',
            name='results_purpose',
            field=models.CharField(choices=[('Для возмещения убытков (ст. 14 ГК КР)', 'Для возмещения убытков (ст. 14 ГК КР)'), ('Для страховой выплаты', 'Для страховой выплаты'), ('Для принятия управленческих решений', 'Для принятия управленческих решений')], default='Для возмещения убытков (ст. 14 ГК КР)', max_length=128, verbose_name='Назначение результатов оценки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='services_table',
            field=models.TextField(blank=True, default='', verbose_name='Таблица услуг (JSON)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vehicle_volume',
            field=models.CharField(default='', max_length=16, verbose_name='Объем ДВС'),
        ),
    ]
