# Generated by Django 3.0.5 on 2020-04-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200426_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='materials_result',
            field=models.IntegerField(default=0, verbose_name='Всего материалов, сом'),
        ),
        migrations.AddField(
            model_name='report',
            name='services_result',
            field=models.IntegerField(default=0, verbose_name='Всего услуг, сом'),
        ),
        migrations.AlterField(
            model_name='report',
            name='additional_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст доп. работ'),
        ),
        migrations.AlterField(
            model_name='report',
            name='disassembly_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст разборок'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hidden_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст скрытых повреждений'),
        ),
        migrations.AlterField(
            model_name='report',
            name='painting_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст окраски'),
        ),
        migrations.AlterField(
            model_name='report',
            name='parts_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст запчастей'),
        ),
        migrations.AlterField(
            model_name='report',
            name='repair_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст ремонтов'),
        ),
    ]
