# Generated by Django 3.0.5 on 2020-04-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200428_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cost_type',
            field=models.CharField(choices=[('1', 'Рыночная стоимость восстановления транспортного средства'), ('2', 'Рыночная стоимость восстановления и утрата товарной стоимости транспортного средства')], default='1', max_length=128, verbose_name='Вид определяемой стоимости'),
        ),
        migrations.AlterField(
            model_name='report',
            name='evaluation_purpose',
            field=models.CharField(choices=[('1', 'Определение стоимости ущерба, причиненного вследствие дорожно-транспортного происшествия'), ('2', 'Определение стоимости ущерба, причиненного вследствие возгорания транспортного средства'), ('3', 'Определение стоимости причиненного ущерба')], default='1', max_length=1, verbose_name='Цель оценки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ownership_identification',
            field=models.CharField(choices=[('1', 'Частная собственность'), ('2', 'Муниципальная собственность'), ('3', 'Государственная собственность'), ('4', 'Н/у')], default='1', max_length=1, verbose_name='Право собственности'),
        ),
        migrations.AlterField(
            model_name='report',
            name='results_purpose',
            field=models.CharField(choices=[('1', 'Для возмещения убытков (ст. 14 ГК КР)'), ('2', 'Для страховой выплаты'), ('3', 'Для принятия управленческих решений')], default='1', max_length=1, verbose_name='Назначение результатов оценки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vehicle_volume',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Объем ДВС'),
        ),
    ]
