# Generated by Django 3.0.5 on 2020-04-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20200428_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cost_type',
            field=models.CharField(choices=[('1', 'Рыночная стоимость восстановления транспортного средства'), ('2', 'Рыночная стоимость восстановления и утрата товарной стоимости транспортного средства')], default='1', max_length=1, verbose_name='Вид определяемой стоимости'),
        ),
    ]
