# Generated by Django 3.0.5 on 2020-04-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200428_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cost_type',
            field=models.CharField(choices=[('0', 'Рыночная стоимость восстановления транспортного средства'), ('1', 'Рыночная стоимость восстановления и утрата товарной стоимости транспортного средства')], default='0', max_length=1, verbose_name='Вид определяемой стоимости'),
        ),
        migrations.AlterField(
            model_name='report',
            name='evaluation_purpose',
            field=models.CharField(choices=[('0', 'Определение стоимости ущерба, причиненного вследствие дорожно-транспортного происшествия'), ('1', 'Определение стоимости ущерба, причиненного вследствие возгорания транспортного средства'), ('2', 'Определение стоимости причиненного ущерба')], default='0', max_length=1, verbose_name='Цель оценки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ownership_identification',
            field=models.CharField(choices=[('0', 'Частная собственность'), ('1', 'Муниципальная собственность'), ('2', 'Государственная собственность'), ('3', 'Н/у')], default='0', max_length=1, verbose_name='Право собственности'),
        ),
        migrations.AlterField(
            model_name='report',
            name='results_purpose',
            field=models.CharField(choices=[('0', 'Для возмещения убытков (ст. 14 ГК КР)'), ('1', 'Для страховой выплаты'), ('2', 'Для принятия управленческих решений')], default='0', max_length=1, verbose_name='Назначение результатов оценки'),
        ),
    ]
