# Generated by Django 3.0.5 on 2020-04-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20200428_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='materials_result',
            field=models.CharField(default=0, max_length=32, verbose_name='Всего материалов, сом'),
        ),
        migrations.AlterField(
            model_name='report',
            name='services_result',
            field=models.CharField(default=0, max_length=32, verbose_name='Всего услуг, сом'),
        ),
    ]
