# Generated by Django 3.0.5 on 2020-04-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20200428_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contract_price',
            field=models.CharField(default='0', max_length=32, verbose_name='Сумма оплаты (договора)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vehicle_mileage',
            field=models.CharField(default='Н/у', max_length=32, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vehicle_volume',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Объем ДВС'),
        ),
    ]
