# Generated by Django 3.0.5 on 2020-06-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20200430_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ass_object',
            field=models.CharField(default='Транспортное средство', max_length=256, verbose_name='Объект оценки'),
        ),
        migrations.AddField(
            model_name='report',
            name='ass_reason',
            field=models.CharField(default='Договор', help_text='Договор, запрос, определение, постановление', max_length=256, verbose_name='Основание оценки'),
        ),
        migrations.AddField(
            model_name='report',
            name='doc_type',
            field=models.CharField(default='Отчет', help_text='Отчет или Заключение', max_length=32, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='report',
            name='exchange_rate',
            field=models.CharField(default='75.0000', max_length=32, verbose_name='Курс доллара к сому'),
        ),
        migrations.AddField(
            model_name='report',
            name='used_methods',
            field=models.CharField(choices=[('0', 'Метод поэлементного расчета затратного подхода и метод рыночной информации сравнительного подхода'), ('1', 'Метод расчета годных остатков затратным подходом и метод рыночной информации сравнительного подхода'), ('2', 'Метод сравнительного анализа продаж')], default='0', max_length=1, verbose_name='Подходы и методы'),
        ),
        migrations.AddField(
            model_name='report',
            name='vehicle_gearbox',
            field=models.CharField(default='Н/у', max_length=32, verbose_name='Тип коробки передач'),
        ),
        migrations.AddField(
            model_name='report',
            name='vehicle_steering',
            field=models.CharField(default='Н/у', max_length=32, verbose_name='Положение руля'),
        ),
        migrations.AlterField(
            model_name='report',
            name='client_name',
            field=models.CharField(default='Н/у', help_text='Введи Ф.И.О. полностью', max_length=256, verbose_name='Ф.И.О. заказчика'),
        ),
        migrations.AlterField(
            model_name='report',
            name='contract_price_in_words',
            field=models.CharField(default='Ноль', max_length=256, verbose_name='Сумма оплаты (прописью)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='inspection_place',
            field=models.CharField(default='Н/у', help_text='Введи хотя бы населенный пункт', max_length=256, verbose_name='Место осмотра:'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_number',
            field=models.CharField(default='000-00/20', help_text='Введи в фомате ннн-мм/гг', max_length=32, verbose_name='Номер отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vehicle_model',
            field=models.CharField(default='Н/у', max_length=256, verbose_name='Марка, модель ТС'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vehicle_type',
            field=models.CharField(default='Н/у', max_length=128, verbose_name='Тип ТС'),
        ),
    ]
