# Generated by Django 3.0.5 on 2020-07-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20200629_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='uts_percent',
            field=models.CharField(default=0, max_length=32, verbose_name='Всего УТС, %'),
        ),
        migrations.AddField(
            model_name='report',
            name='uts_table',
            field=models.TextField(blank=True, default='', verbose_name='Таблица УТС (JSON)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cost_type',
            field=models.CharField(choices=[('0', 'Рыночная стоимость восстановления'), ('1', 'Рыночная стоимость восстановления и утрата товарной стоимости')], default='0', max_length=1, verbose_name='Вид определяемой стоимости'),
        ),
    ]
