# Generated by Django 3.0.5 on 2020-07-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20200705_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='total_result',
            field=models.CharField(default=0, max_length=32, verbose_name='Всего материалов и услуг, сом'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vehicle_frame',
            field=models.CharField(default='-', max_length=32, verbose_name='Номер рамы (шасси)'),
        ),
    ]
