# Generated by Django 3.0.5 on 2020-07-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20200709_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='damaged_body_parts_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст осмотра'),
        ),
        migrations.AddField(
            model_name='report',
            name='damaged_other_parts_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст осмотра'),
        ),
        migrations.AddField(
            model_name='report',
            name='definition_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст осмотра'),
        ),
        migrations.AddField(
            model_name='report',
            name='kop',
            field=models.IntegerField(default=0.5, verbose_name='Коп'),
        ),
        migrations.AddField(
            model_name='report',
            name='kv',
            field=models.IntegerField(default=0.35, verbose_name='Кв'),
        ),
        migrations.AddField(
            model_name='report',
            name='kz',
            field=models.IntegerField(default=0.7, verbose_name='Кз'),
        ),
        migrations.AddField(
            model_name='report',
            name='ost_percent',
            field=models.CharField(default=0, max_length=32, verbose_name='Всего остатков, %'),
        ),
        migrations.AddField(
            model_name='report',
            name='ost_table',
            field=models.TextField(blank=True, default='', verbose_name='Таблица остатков (JSON)'),
        ),
        migrations.AddField(
            model_name='report',
            name='unbroken_parts_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст осмотра'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cost_type',
            field=models.CharField(choices=[('0', 'Рыночная стоимость восстановления'), ('1', 'Рыночная стоимость восстановления и утрата товарной стоимости'), ('2', 'Рыночная стоимость годных остатков (утилизационная стоимость)'), ('3', 'Рыночная стоимость годных остатков (утилизационная стоимость)')], default='0', max_length=1, verbose_name='Вид определяемой стоимости'),
        ),
    ]
