# Generated by Django 3.0.5 on 2020-07-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20200725_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='damaged_body_parts_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст повреждений кузова'),
        ),
        migrations.AlterField(
            model_name='report',
            name='damaged_other_parts_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст прочих повреждений'),
        ),
        migrations.AlterField(
            model_name='report',
            name='unbroken_parts_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст уцелевших деталей'),
        ),
    ]
