# Generated by Django 3.0.5 on 2020-07-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20200726_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='used_methods',
            field=models.CharField(choices=[('0', 'Метод поэлементного расчета затратного подхода и метод рыночной информации сравнительного подхода'), ('1', 'Метод расчета годных остатков затратным подходом и метод рыночной информации сравнительного подхода'), ('2', 'Метод сравнительного анализа продаж'), ('3', 'Методы поэлементного расчета восстановления и годных остатков затратными подходами, метод рыночной информации сравнительного подхода')], default='0', max_length=1, verbose_name='Подходы и методы'),
        ),
    ]
