# Generated by Django 3.0.5 on 2020-07-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20200726_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='kop',
            field=models.CharField(default='0.5', max_length=32, verbose_name='Коп'),
        ),
        migrations.AlterField(
            model_name='report',
            name='kv',
            field=models.CharField(default='0.35', max_length=32, verbose_name='Кв'),
        ),
        migrations.AlterField(
            model_name='report',
            name='kz',
            field=models.CharField(default='0.7', max_length=32, verbose_name='Кз'),
        ),
    ]
