# Generated by Django 3.0.5 on 2020-12-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20200727_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='parts_table',
            field=models.TextField(blank=True, default='', verbose_name='Таблица запчастей (JSON)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='used_methods',
            field=models.CharField(choices=[('0', 'Метод поэлементного расчета затратного подхода и метод рыночной информации сравнительного подхода'), ('1', 'Метод поэлементного расчета затратного подхода и метод рыночной информации сравнительного подхода'), ('2', 'Метод расчета годных остатков затратным подходом и метод рыночной информации сравнительного подхода'), ('3', 'Методы поэлементного расчета восстановления и годных остатков затратными подходами, метод рыночной информации сравнительного подхода')], default='0', max_length=1, verbose_name='Подходы и методы'),
        ),
    ]
