# Generated by Django 4.1.4 on 2025-08-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_report_ui_state_alter_report_results_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='inspection_text_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_data_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='vehicle_data_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='results_purpose',
            field=models.CharField(choices=[('0', 'Для страховой выплаты'), ('1', 'Для возмещения убытков (ст. 14 ГК КР)'), ('2', 'Для принятия управленческих решений')], default='1', max_length=1, verbose_name='Назначение результатов оценки'),
        ),
    ]
