# Generated by Django 4.1.4 on 2025-11-11 12:10

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_reportphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportphoto',
            name='image',
            field=models.ImageField(upload_to=reports.models.report_photo_upload_to),
        ),
    ]
