# Generated by Django 4.1.4 on 2025-11-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_alter_reportphoto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportphoto',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='reportphoto',
            name='image',
            field=models.ImageField(upload_to='report_photos/%Y/%m/%d'),
        ),
    ]
