# Generated by Django 4.1.4 on 2025-11-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_alter_reportphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='phone_contacts',
            field=models.TextField(blank=True, default='', verbose_name='Контакты по запчастям (телефоны)'),
        ),
    ]
